{
 "title": "Nvidia GPU Stats",
 "tags": [
  "nixos",
  "prometheus",
  "gpu",
  "nvidia"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(nvidia_smi_utilization_gpu_ratio, job)"
   },
   {
    "name": "instance",
    "query": "label_values(nvidia_smi_utilization_gpu_ratio{job=~\"$job\"}, instance)"
   },
   {
    "name": "gpu",
    "query": "label_values(nvidia_smi_utilization_gpu_ratio{job=~\"$job\", instance=~\"$instance\"}, uuid)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{job=~\"$job\",instance=~\"$instance\",uuid=~\"$gpu\"}",
     "legendFormat": "{{instance}} GPU"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{job=~\"$job\",instance=~\"$instance\",uuid=~\"$gpu\"}",
     "legendFormat": "{{instance}} Mem"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{job=~\"$job\",instance=~\"$instance\",uuid=~\"$gpu\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "nvidia_smi_memory_total_bytes{job=~\"$job\",instance=~\"$instance\",uuid=~\"$gpu\"}",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{job=~\"$job\",instance=~\"$instance\",uuid=~\"$gpu\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}