{ ... }:
{
  imports = [
    ./ssh.nix
    ./jellyfin.nix
    ./jackett.nix
    ./prowlarr.nix
    ./transmission.nix
    ./cross-seed.nix
    ./tvheadend.nix
    ./threadfin.nix
    ./testaustime-backup.nix
    ./syncthing.nix
    ./samba.nix
    ./xserver.nix
    ./gpg.nix
    ./vaultwarden.nix
    ./restic.nix
    ./backup-notify.nix
    ./niri.nix
    ./website.nix
    ./ip-echo.nix
    ./sonarr.nix
    ./uptime-kuma.nix
    ./mailserver.nix
    ./webmail.nix
    ./dyndns.nix
    ./smartd.nix
    ./formicer-website.nix
    ./nixarr.nix
    ./gatus.nix
    ./headscale.nix
    ./hedgedoc.nix
    ./tailscale.nix
    ./nginx.nix
    ./zfs-backup
    ./vpn.nix
    ./adguardhome.nix
    ./coredns.nix
    ./nextcloud.nix
    ./memegenerator.nix
    ./cheese
    ./crabfit.nix
    ./yensid.nix
    ./prometheus.nix
    ./typst-collab.nix
    ./resource-limits.nix
    ./email-telegram-bridge.nix
    ./attic.nix
    ./matrix.nix
    ./minecraft.nix
    ./screego.nix
    ./k9mail-link.nix
  ];
}
